# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.290
  hooks:
    # Run the linter.
    - id: ruff
      args: [ src/main.py ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: ''
  hooks:
    - id: mypy
