WEATHER_ICON_DAY = {
    "thunderstorm with light rain": "11d.png",
    "thunderstorm with rain": "11d.png",
    "thunderstorm with heavy rain": "11d.png",
    "light thunderstorm": "11d.png",
    "thunderstorm": "11d.png",
    "heavy thunderstorm": "11d.png",
    "ragged thunderstorm": "11d.png",
    "thunderstorm with light drizzle": "11d.png",
    "thunderstorm with drizzle": "11d.png",
    "thunderstorm with heavy drizzle": "11d.png",

    "light intensity drizzle": "09d.png",
    "drizzle": "09d.png",
    "heavy intensity drizzle": "09d.png",
    "light intensity drizzle rain": "09d.png",
    "drizzle rain": "09d.png",
    "heavy intensity drizzle rain": "09d.png",
    "shower rain and drizzle": "09d.png",
    "heavy shower rain and drizzle": "09d.png",
    "shower drizzle": "09d.png",

    "light rain": "10d.png",
    "moderate rain": "10d.png",
    "heavy intensity rain": "10d.png",
    "very heavy rain": "10d.png",
    "extreme rain": "10d.png",
    "freezing rain": "13d.png",
    "light intensity shower rain": "09d.png",
    "shower rain": "09d.png",
    "heavy intensity shower rain": "09d.png",
    "ragged shower rain": "09d.png",

    "light snow": "13d.png",
    "snow": "13d.png",
    "heavy snow": "13d.png",
    "sleet": "13d.png",
    "light shower sleet": "13d.png",
    "shower sleet": "13d.png",
    "light rain and snow": "13d.png",
    "rain and snow": "13d.png",
    "light shower snow": "13d.png",
    "shower snow": "13d.png",
    "heavy shower snow": "13d.png",

    "mist": "50d.png",
    "smoke": "50d.png",
    "haze": "50d.png",
    "sand/dust whirls": "50d.png",
    "fog": "50d.png",
    "sand": "50d.png",
    "dust": "50d.png",
    "volcanic ash": "50d.png",
    "squalls": "50d.png",
    "tornado": "50d.png",

    "clear sky": "01d.png",
    
    "few clouds": "02d.png",
    "scattered clouds": "03d.png",
    "broken clouds": "04d.png",
    "overcast clouds": "04d.png", 
}


WEATHER_ICON_HIGHT = {
    "thunderstorm with light rain": "11n.png",
    "thunderstorm with rain": "11n.png",
    "thunderstorm with heavy rain": "11n.png",
    "light thunderstorm": "11n.png",
    "thunderstorm": "11n.png",
    "heavy thunderstorm": "11n.png",
    "ragged thunderstorm": "11n.png",
    "thunderstorm with light drizzle": "11n.png",
    "thunderstorm with drizzle": "11n.png",
    "thunderstorm with heavy drizzle": "11n.png",

    "light intensity drizzle": "09n.png",
    "drizzle": "09n.png",
    "heavy intensity drizzle": "09n.png",
    "light intensity drizzle rain": "09n.png",
    "drizzle rain": "09n.png",
    "heavy intensity drizzle rain": "09n.png",
    "shower rain and drizzle": "09n.png",
    "heavy shower rain and drizzle": "09n.png",
    "shower drizzle": "09n.png",

    "light rain": "10n.png",
    "moderate rain": "10n.png",
    "heavy intensity rain": "10n.png",
    "very heavy rain": "10n.png",
    "extreme rain": "10n.png",
    "freezing rain": "13n.png",
    "light intensity shower rain": "09n.png",
    "shower rain": "09n.png",
    "heavy intensity shower rain": "09n.png",
    "ragged shower rain": "09n.png",

    "light snow": "13n.png",
    "snow": "13n.png",
    "heavy snow": "13n.png",
    "sleet": "13n.png",
    "light shower sleet": "13n.png",
    "shower sleet": "13n.png",
    "light rain and snow": "13n.png",
    "rain and snow": "13n.png",
    "light shower snow": "13n.png",
    "shower snow": "13n.png",
    "heavy shower snow": "13n.png",

    "mist": "50n.png",
    "smoke": "50n.png",
    "haze": "50n.png",
    "sand/dust whirls": "50n.png",
    "fog": "50n.png",
    "sand": "50n.png",
    "dust": "50n.png",
    "volcanic ash": "50n.png",
    "squalls": "50n.png",
    "tornado": "50n.png",

    "clear sky": "01n.png",
    
    "few clouds": "02n.png",
    "scattered clouds": "03n.png",
    "broken clouds": "04n.png",
    "overcast clouds": "04n.png", 
}